### ISSUE TITLE
Remove lib/grove.js and add a gitignore to prevent oneshot compilations from being committed.

### ISSUE THREAD

**Issue by willmtemple** [LaboratoryForPlayfulComputation/pxexec-runtime#2]
@TannerQuigley , the build artifact for grove.ts was accidentally committed and pushed to this repository in `lib/grove.js`. Build artifacts should always be generated in `out/` unless you're running `tsc` on a file directly, in which case you will need to check and make sure that no artifacts get committed to the repo.

**Comment by TannerQuigley** [comment]
I just added /lib/*.js to gitignore so that all js files in lib will be ignored. Is that the best way to ignore artifacts?

**Comment by willmtemple** [comment]
Should do the trick.
